import "unknwn.idl";
import "ocidl.idl";

[uuid(b9684566-2c89-11ee-be56-0242ac120002)]
library RainbowTaskbarDLL {
    [uuid(c9d60190-2c89-11ee-be56-0242ac120002)]
    coclass TAPSite 
    {
        interface IObjectWithSite;
    }

    [uuid(5a71c99f-5386-48a9-9165-de45a6a305ff)]
    coclass AppearanceServiceAPI 
    {
        interface IDispatch;
    }


}